import os
import vtk
import numpy as np
import logging
from utils import utils

def create_medial_sheet(path):
    """
    Generates a medial sheet of the myocardium by taking the inner surface 
    and displacing the points 50% along the thickness vectors.
    """
    logging.info(f"Creating medial sheet for: {path}")
    
    # Paths to the files already generated by thickness_estimation.py
    mesh_path = os.path.join(path, "surfaces", "dist_source.vtk")
    vec_path = os.path.join(path, "misc", "vectors.npz")
    out_path = os.path.join(path, "surfaces", "medial_sheet.vtk")
    
    # Check if files exist
    if not os.path.exists(mesh_path):
        logging.error(f"Could not find the source mesh: {mesh_path}")
        return
    if not os.path.exists(vec_path):
        logging.error(f"Could not find the vector file: {vec_path}")
        return
        
    try:
        # Load the inner mesh using your existing utils module
        mesh = utils.read_vtk_mesh(mesh_path)
        
        # Load the vectors (from source to target)
        loaded = np.load(vec_path)
        vectors = loaded["vectors"]
        
        num_points = mesh.GetNumberOfPoints()
        
        # Safety check: Ensure the number of points and vectors match
        if num_points != len(vectors):
            logging.error(f"Mismatch! Mesh has {num_points} points, but there are {len(vectors)} vectors.")
            return
            
        # Create a new set of points for the medial sheet
        new_points = vtk.vtkPoints()
        for i in range(num_points):
            # Get the original point
            p = np.array(mesh.GetPoint(i))
            # Get the corresponding vector
            v = vectors[i]
            
            # Calculate the midpoint (50% of the distance)
            medial_p = p + 0.5 * v
            new_points.InsertNextPoint(medial_p)
            
        # Create the new mesh by copying the topology from the old one, but with the new points
        medial_mesh = vtk.vtkPolyData()
        medial_mesh.DeepCopy(mesh)
        medial_mesh.SetPoints(new_points)
        
        # Save the new mesh
        utils.write_vtk_mesh(medial_mesh, out_path)
        logging.info(f"Medial sheet successfully saved: {out_path}")
        
    except Exception as e:
        logging.error(f"An error occurred while creating the medial sheet for {path}: {e}")

if __name__ == "__main__":
    # Test code if you run the file directly
    print("This module is intended to be imported by main_pipeline.py")